import { addQuotes } from '@/lib/quotes'
import { quotePools, expandQuotes } from '@/lib/quotePools'
import { NextResponse } from 'next/server'
  'Love Quotes': [
    "Love is composed of a single soul inhabiting two bodies.",
    "The best thing to hold onto in life is each other.",
    "I love you not only for what you are, but for what I am when I am with you.",
    "Love is when the other person's happiness is more important than your own.",
    "In all the world, there is no heart for me like yours.",
    "You are my today and all of my tomorrows.",
    "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
    "Love is not about how much you say 'I love you', but how much you prove that it's true.",
    "The best love is the kind that awakens the soul and makes us reach for more.",
    "I would rather spend one lifetime with you, than face all the ages of this world alone.",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    "The greatest thing you'll ever learn is just to love and be loved in return.",
    "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.",
    "A successful marriage requires falling in love many times, always with the same person.",
    "Love is friendship that has caught fire.",
    "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.",
    "Love doesn't make the world go round. Love is what makes the ride worthwhile.",
    "I need you like a heart needs a beat.",
    "You are my sunshine, my only sunshine.",
    "I fell in love with you because of the million things you never knew you were doing.",
    "Love is not finding someone to live with. It's finding someone you can't live without.",
    "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    "I love you more than I have ever found a way to say to you.",
    "Love is being stupid together.",
    "The best thing to hold onto in life is each other.",
    "I love you to the moon and back.",
    "You are my heart, my life, my one and only thought.",
    "Love is like the wind, you can't see it but you can feel it.",
    "I love you not because of who you are, but because of who I am when I am with you.",
    "You are my paradise and I would happily get stranded on you for a lifetime.",
    "I love you more than words can express.",
    "You are the reason I believe in love.",
    "Every love story is beautiful, but ours is my favorite.",
    "I want to be with you until the sun falls from the sky.",
    "You are my today and all of my tomorrows.",
    "I love you more than coffee, and that's saying a lot.",
    "You are my favorite place to go when my mind searches for peace.",
    "I love you to infinity and beyond.",
    "You are my person.",
    "I love you not only for what you are, but for what I am when I am with you.",
    "You are my sunshine on a cloudy day.",
    "I love you more than all the stars in the sky.",
    "You are my heart's desire.",
    "I love you more than yesterday, but less than tomorrow.",
    "You are my happy place.",
    "I love you beyond words, beyond measure, beyond time.",
    "You are my everything.",
    "I love you more than life itself.",
    "You are my dream come true.",
    "I love you to the moon and back, infinity times.",
    "You are my always and forever.",
  ],
  'Attitude Status': [
    "I don't need a perfect person, I need someone who makes me feel perfect.",
    "My attitude is based on how you treat me.",
    "I'm not perfect, but I'm limited edition.",
    "I am who I am, and I don't need to prove anything to anyone.",
    "I don't follow the crowd, I make my own path.",
    "My attitude is my choice, and I choose to be positive.",
    "I'm not here to be perfect, I'm here to be real.",
    "I don't need your approval to be myself.",
    "My attitude is my superpower.",
    "I'm not rude, I'm just honest and you're not used to it.",
    "I don't have an attitude problem. You have a perception problem.",
    "My attitude is based on how you treat me. Treat me well, and I'll treat you better.",
    "I'm not trying to be perfect, I'm trying to be the best version of myself.",
    "I don't care what people think of me. I care what I think of myself.",
    "My attitude is my choice, and I choose to be happy.",
    "I'm not here to impress anyone. I'm here to be myself.",
    "I don't need validation from others. I validate myself.",
    "My attitude reflects my leadership.",
    "I'm not arrogant, I'm confident. There's a difference.",
    "I don't follow trends. I set them.",
    "My attitude is my brand.",
    "I'm not competing with anyone. I'm competing with myself.",
    "I don't need to be liked by everyone. I need to be respected.",
    "My attitude is my weapon.",
    "I'm not here to fit in. I'm here to stand out.",
    "I don't need your permission to be great.",
    "My attitude is my armor.",
    "I'm not trying to be better than anyone else. I'm trying to be better than I was yesterday.",
    "I don't need to explain myself to anyone.",
    "My attitude is my strength.",
    "I'm not here to please everyone. I'm here to be authentic.",
    "I don't need your opinion to validate my worth.",
    "My attitude is my power.",
    "I'm not here to be liked. I'm here to be respected.",
    "I don't need to prove anything to anyone.",
    "My attitude is my identity.",
    "I'm not here to follow. I'm here to lead.",
    "I don't need your approval to succeed.",
    "My attitude is my legacy.",
    "I'm not here to blend in. I'm here to shine.",
    "I don't need to be perfect. I need to be authentic.",
    "My attitude is my signature.",
    "I'm not here to be average. I'm here to be extraordinary.",
    "I don't need your validation. I validate myself.",
    "My attitude is my statement.",
    "I'm not here to be ordinary. I'm here to be legendary.",
    "I don't need to fit in. I need to stand out.",
    "My attitude is my reputation.",
  ],
  'Shayari': [
    "Dil ki baat labon tak aayi, Shayari ban kar rah gayi.",
    "Mohabbat ek aisi kitaab hai, Jise padh kar dil ko sukoon milta hai.",
    "Zindagi mein kuch pal aise aate hain, Jo hamesha yaad rahte hain.",
    "Dil se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Mohabbat ka matlab samjha nahi, Par dil ne man li hai.",
    "Aankhon mein khwab hai, Dil mein umeed hai, Zindagi mein tum ho.",
    "Dil ki dhadkan tumse milti hai, Har saans tumhari yaad deti hai.",
    "Mohabbat ki raah mein, Har kadam naya safar hai.",
    "Dil se jo nikli hai baat, Woh shayari hai yaad.",
    "Tumhari yaadon mein kho jata hoon, Har pal tumhare saath rehta hoon.",
    "Dil ki baat kya hai, Shayari mein chhupi hai.",
    "Mohabbat ki raah mein, Har pal naya safar hai.",
    "Aankhon se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Dil se jo nikli hai baat, Woh shayari hai yaad.",
    "Zindagi mein kuch pal aise aate hain, Jo hamesha yaad rahte hain.",
    "Mohabbat ek aisi baat hai, Jo har dil ko pasand hai.",
    "Dil ki dhadkan tumhari yaad deti hai, Har pal tumhare saath rehta hoon.",
    "Tumhari yaadon mein kho jata hoon, Har saans tumhari yaad deti hai.",
    "Mohabbat ki raah mein, Har kadam naya safar hai.",
    "Dil se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Aankhon mein khwab hai, Dil mein umeed hai, Zindagi mein tum ho.",
    "Dil ki baat labon tak aayi, Shayari ban kar rah gayi.",
    "Mohabbat ek aisi kitaab hai, Jise padh kar dil ko sukoon milta hai.",
    "Zindagi mein kuch pal aise aate hain, Jo hamesha yaad rahte hain.",
    "Dil se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Mohabbat ka matlab samjha nahi, Par dil ne man li hai.",
    "Aankhon mein khwab hai, Dil mein umeed hai, Zindagi mein tum ho.",
    "Dil ki dhadkan tumse milti hai, Har saans tumhari yaad deti hai.",
    "Mohabbat ki raah mein, Har kadam naya safar hai.",
    "Dil se jo nikli hai baat, Woh shayari hai yaad.",
    "Tumhari yaadon mein kho jata hoon, Har pal tumhare saath rehta hoon.",
    "Dil ki baat kya hai, Shayari mein chhupi hai.",
    "Mohabbat ki raah mein, Har pal naya safar hai.",
    "Aankhon se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Dil se jo nikli hai baat, Woh shayari hai yaad.",
    "Zindagi mein kuch pal aise aate hain, Jo hamesha yaad rahte hain.",
    "Mohabbat ek aisi baat hai, Jo har dil ko pasand hai.",
    "Dil ki dhadkan tumhari yaad deti hai, Har pal tumhare saath rehta hoon.",
    "Tumhari yaadon mein kho jata hoon, Har saans tumhari yaad deti hai.",
    "Mohabbat ki raah mein, Har kadam naya safar hai.",
    "Dil se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Aankhon mein khwab hai, Dil mein umeed hai, Zindagi mein tum ho.",
    "Dil ki baat labon tak aayi, Shayari ban kar rah gayi.",
    "Mohabbat ek aisi kitaab hai, Jise padh kar dil ko sukoon milta hai.",
    "Zindagi mein kuch pal aise aate hain, Jo hamesha yaad rahte hain.",
    "Dil se nikli hai jo baat, Woh shayari ban kar rah gayi.",
    "Mohabbat ka matlab samjha nahi, Par dil ne man li hai.",
    "Aankhon mein khwab hai, Dil mein umeed hai, Zindagi mein tum ho.",
    "Dil ki dhadkan tumse milti hai, Har saans tumhari yaad deti hai.",
  ],
  'Motivation Quotes': [
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "You are never too old to set another goal or to dream a new dream.",
    "The way to get started is to quit talking and begin doing.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only person you are destined to become is the person you decide to be.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream big and dare to fail.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big things happen.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream without fear. Love without limits.",
    "Be so good they can't ignore you.",
    "Work hard in silence, let your success be your noise.",
    "If you want to achieve greatness, stop asking for permission.",
    "The only way to do great work is to love what you do.",
    "If you can dream it, you can do it.",
    "Your life is your message to the world. Make sure it's inspiring.",
    "Don't let yesterday take up too much of today.",
    "You are never too old to set another goal or to dream a new dream.",
    "The way to get started is to quit talking and begin doing.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only person you are destined to become is the person you decide to be.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream big and dare to fail.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
  ],
  'Festival Wishes': [
    "May this festival bring joy, happiness, and prosperity to your life. Happy Diwali!",
    "Wishing you a year filled with happiness, success, and new opportunities. Happy New Year!",
    "May the colors of Holi fill your life with happiness and joy. Happy Holi!",
    "May this Eid bring peace, happiness, and prosperity to your life. Eid Mubarak!",
    "Wishing you a Christmas filled with love, joy, and happiness. Merry Christmas!",
    "May this festival bring you closer to your loved ones. Happy celebrations!",
    "Wishing you and your family a very happy and prosperous festival!",
    "May the divine blessings of this festival bring you peace and happiness!",
    "Hope this festival brings lots of happiness and success in your life!",
    "Wishing you a wonderful festival filled with love, laughter, and joy!",
    "May this festive season bring you endless joy and prosperity!",
    "Wishing you and your family a very happy and blessed festival!",
    "May the spirit of this festival fill your heart with happiness!",
    "Hope this festival brings you closer to your dreams!",
    "Wishing you a festival full of love, laughter, and wonderful memories!",
    "May the divine light of this festival illuminate your life!",
    "Wishing you peace, prosperity, and happiness this festival season!",
    "May this festival bring you closer to your loved ones!",
    "Hope this festival brings you lots of joy and success!",
    "Wishing you a blessed and joyful festival!",
    "May this festival fill your life with happiness and prosperity!",
    "Wishing you and your family a very happy festival!",
    "May the blessings of this festival be with you always!",
    "Hope this festival brings you closer to your goals!",
    "Wishing you a festival full of love and happiness!",
    "May this festival bring you endless joy and success!",
    "Wishing you a very happy and prosperous festival!",
    "May the divine blessings of this festival be with you!",
    "Hope this festival brings you lots of happiness!",
    "Wishing you a blessed and joyful festival season!",
    "May this festival fill your heart with happiness!",
    "Wishing you and your family a very happy festival!",
    "May the blessings of this festival be with you always!",
    "Hope this festival brings you closer to your dreams!",
    "Wishing you a festival full of love and joy!",
    "May this festival bring you endless happiness!",
    "Wishing you a very happy and blessed festival!",
    "May the divine light of this festival illuminate your life!",
    "Hope this festival brings you lots of joy!",
    "Wishing you a blessed and joyful festival!",
    "May this festival fill your life with happiness!",
    "Wishing you and your family a very happy festival!",
    "May the blessings of this festival be with you always!",
    "Hope this festival brings you closer to your goals!",
    "Wishing you a festival full of love and happiness!",
    "May this festival bring you endless joy and success!",
    "Wishing you a very happy and prosperous festival!",
    "May the divine blessings of this festival be with you!",
    "Hope this festival brings you lots of happiness!",
  ],
}


export async function POST(request) {
  try {
    const { category, count = 300 } = await request.json().catch(() => ({}))
    
    const categories = category 
      ? [category] 
      : ['Love Quotes', 'Attitude Status', 'Shayari', 'Motivation Quotes', 'Festival Wishes']
    
    let totalAdded = 0
    
    for (const cat of categories) {
      const expandedQuotes = expandQuotes(cat, count)
      const quotesToAdd = expandedQuotes.map(text => ({
        text,
        category: cat,
        author: 'Unknown',
      }))
      
      if (quotesToAdd.length > 0) {
        addQuotes(quotesToAdd)
        totalAdded += quotesToAdd.length
        console.log(`✅ Added ${quotesToAdd.length} quotes to ${cat}`)
      }
    }
    
    return NextResponse.json({ 
      success: true, 
      message: `Successfully added ${totalAdded} quotes`,
      quotesAdded: totalAdded,
      categories: categories,
    })
  } catch (error) {
    console.error('Error initializing quotes:', error)
    return NextResponse.json({ 
      success: false, 
      error: error.message 
    }, { status: 500 })
  }
}

export async function GET(request) {
  return NextResponse.json({ 
    message: 'Use POST method to initialize quotes',
    endpoint: '/api/init',
    usage: 'POST with { "category": "Love Quotes", "count": 300 } or { "count": 300 } for all categories'
  })
}

